### ISSUE TITLE
Multiple JSONHandler.Parse() calls

### ISSUE THREAD

**Issue by a--f** [CarlosGtrz/ClarionJson#1]
Hi,

I noticed that there is a bug with in the JSONHandler.Reset() method causing successive JSONHandler.Parse() calls to fail (i.e. not parse anything but returning an empty JSONObject). This is due to the variable EOF that is not resetted to FALSE. I suggest to add "SELF.EOF = FALSE" to JSONHandler.Reset() in the JSONHandler.clw file.

Regards
Andreas

**Comment by CarlosGtrz** [comment]
Hi Andreas,

Done, thanks for reporting.
