### ISSUE TITLE
Examples

### ISSUE THREAD

**Issue by AdriaanDUP79** [CarlosGtrz/ClarionJson#2]
Good day,

Do you have any possible examples that a person can work from?

**Comment by CarlosGtrz** [comment]
Ok, I'll write a few examples

**Comment by CarlosGtrz** [comment]
Just added a project. In TestJSON.clw  you can find a few basic examples of how to use the classes. 

If you have a particular need, post an example here and I'll try to look into it.

**Comment by CarlosGtrz** [comment]
Just added a project. In JSONObject.clw  you can find a few basic examples of how to use the classes. If you have a particular need,
